title: Sudeep Biswas
title_separator: "|"
email: sudeepbiswas02@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sudeep Biswas - A tech enthusiast, working primarily on open source Ethereum projects.
  I am an SAP ABAP developer full-time, but I spend most of my non-working hours working and reading about Blockchain projects.
twitter_username: sudeepbiswas02
github_username: sudeepb02
minimal_mistakes_skin: default
search: true
search_full_content: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sudeep Biswas"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Actively looking for opportunities in the Blockchain space"
  location: "Hyderabad, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sudeepbiswas02@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sudeepbiswas02"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sudeepb02"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sudeepbiswas02"

#Social links
social:
  type: "Person"
  name: "Sudeep Biswas"
  links:
    - "https://twitter.com/sudeepbiswas02"
    - "https://github.com/sudeepb02"
    - "https://linkedin.com/in/sudeepbiswas02"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sudeepbiswas02"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sudeepb02"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sudeepbiswas02"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
